# Generated by Django 5.2.6 on 2025-09-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_alter_products_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
