# Generated by Django 5.2.6 on 2025-09-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='item_sales',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
